[package]
name = "ydcv"
version = "0.1.1"
authors = ["passchaos"]

[dependencies]
hyper = "0.9"
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
ansi_term = "0.8"
rocksdb = "0.4"
log = "0.3"
env_logger = "0.3"
getopts = "0.2"
