[package]
name = "ydcv"
version = "0.2.0"
authors = ["passchaos"]

[dependencies]
hyper = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
ansi_term = "*"
rocksdb = "*"
slog = "*"
slog-envlogger = "*"
slog-term = "*"
slog-scope = "*"
clap = "*"
